# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\Codinglife\Python_project\SRT-learner\qwidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(568, 499)
        self.inputLineEdit = QtWidgets.QLineEdit(Form)
        self.inputLineEdit.setGeometry(QtCore.QRect(60, 80, 291, 51))
        self.inputLineEdit.setObjectName("inputLineEdit")
        self.inputLabel = QtWidgets.QLabel(Form)
        self.inputLabel.setGeometry(QtCore.QRect(60, 20, 311, 61))
        font = QtGui.QFont()
        font.setFamily("钉钉进步体")
        font.setPointSize(16)
        self.inputLabel.setFont(font)
        self.inputLabel.setObjectName("inputLabel")
        self.inputPush = QtWidgets.QPushButton(Form)
        self.inputPush.setGeometry(QtCore.QRect(350, 150, 75, 23))
        self.inputPush.setObjectName("inputPush")
        self.answerlist = QtWidgets.QListView(Form)
        self.answerlist.setGeometry(QtCore.QRect(60, 210, 256, 192))
        self.answerlist.setObjectName("answerlist")

        self.retranslateUi(Form)
        self.inputPush.clicked.connect(self.answerlist.doItemsLayout) # type: ignore
        
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.inputLabel.setText(_translate("Form", "请输入你想查询的台词"))
        self.inputPush.setText(_translate("Form", "确认"))
